version: '3.5'

services:
  grow-web:
    container_name: grow-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 251:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - grow-be
    networks:
      - grow-network

  grow-be:
    container_name: grow-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=grow
    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - grow-network
networks:
  grow-network:
    external: true
